#+Bibliography: /home/cpsoz/Github/rom/CP-ROM.bib

Im Oeuvre Reinhold Sackmanns hat uns einen Ansatz besonders interessiert, den er im Rahmen seiner unterschiedlichen Arbeiten zur Demographie, zur Lebenslaufsoziologie und zu gesellschaftlichen Instanzen der Sozialisation wie den (Hoch)Schulen, dem Arbeitsmarkt oder dem Rentensystem entwickelt hat. Dieser Ansatz finden wir in seinen Arbeiten unterschiedlich ausgedruckt. Nehmen wir etwa die Schlussfolgerungen seiner Habilitationsschrift, wenn er eine Bilanz zur Lebenslaufsoziologie wie folgt zieht: "An den Anfängen dieser Disziplin (...) stand die Vorstellung, daß Alter neben seiner biologischen Komponente auch gesellschaftlich kulturelle Elemente enthält. Gesellschaft war ein Nebenfaktor, der wahrgenommen werden sollte. In der Theorie des institutionalisierten Lebenslaufs gewann die Vorstellung Kontur, daß die modernen gesellschaftlichen Institutionen (...) spezifische Lebensläufe kontitutieren" [cite:@sackmann98:_konkur_gener_arbeit, 228-229]. Dabei legt Sackmann nah, dass sich die künftige Forschung in der Lebenslaufsoziologie mit der Art und Weise auseinandersetzen sollte, wie Lebensläufe als eingebettete Prozesse an der Schnittstelle der Biographien von Akteuren und der formalen Operationen von gesellschaftlichen Instanzen entstehen und von einer solchen Einbettung strukturiert werden. "Lebensläufe", wie er in einem späteren Beitrag sagt, "vollziehen sich eingebettet, in Gruppen, in Gemeinschaften, Gesellschaften und v.a. Organisationen" [cite:@sackmann07:_leben_biogr, 206]. Dieser Ansatz ist aus den folgenden Gründen interessant.

Sackmann versteht Lebensläufe nicht mehr im geläufigen soziologischen Sinn von "trajectoires", die den Fokus auf den Weg der Akteure von gesellschaftlichen Instanzen der Sozialisation zu weiteren gesellschaftlichen Instanzen der Sozialisation setzen. Damit wird gesagt, das gesellschaftliche Sozialisationsinstanzen wie etwa (Hoch)Schulen oder Arbeitsmarkt mehr als nur "verpflichtende Anlaufstationen" von Akteuren sind [cite:@latour05:_reass_social], die Akteure registrieren würden und je nach Sozialisationserfolg unterschiedlich auf weitere gesellschaftliche Bahnen umverteilen würden. Gesellschaftliche Instanzen sind keine irreflexive Orte der Vergebung von Titeln und Rechten, sondern sie geben den Akteuren Einschreibungsmöglichkeiten in der Gesellschaft und reflektieren entsprechend über ihre Rolle in diesem Zusammenhang. Auch zu diesem Zweck entwickeln gesellschaftliche Instanzen dauernd formale Verfahren, die Orientierungsmuster bzw. "Leitbilder" für die Akteure schaffen und deshalb auf ihre Laufbahnen wirken [cite:@sackmann07:_leben_biogr, 206]. Dass eine solche Wirkung auch unintendierte Folgen hat und Ungleichheiten zwischen Akteuren bzw. Akteurgenerationen generiert, hat Sackmann mehrmals im Sinne einer kritischen soziologischen Betrachtung von gesellschaftlichen Instanzen unterstrichen [cite: vgl. etwa @sackmann15:_bedeut_auswah_erzeug_bildun; vgl. auch @sackmann19:_mechan_eliteb]. Aber eine kritische Betrachtung von gesellschaftlichen Instanzen reicht allein nicht aus. Nach Sackmann müssen ebenfalls Korrekturmaßnahmen von gesellschaftlichen Instanzen abgebildet werden, die darauf abzielen, Maßnahmen und entsprechende formale Verfahren zur Einschränkungen bzw. Schrumpfung der Ungleichheitsproduktion zu definieren.

Mit diesem konstruktiven Korrelat zur kritischen Betrachtung von gesellschaftlichen Instanzen bringt Sackmann seinen Ansatz zur Vollendung: Weil Kollektivakteure als Teil des Einschreibungskontextes fungieren, den sie mit den Akteuren aufbauen und innerhalb dessen die Laufbahn von solchen Akteuren strukturiert wird, ist es aus Sicht einer soziologischen Makroperspektive nicht ausreichend, nur die Defizite von Kollektivakteuren in ihren Wechselwirkungen mit Einzelakteuren hervorzuheben. Es muss ebenfalls verstanden werden, wie gesellschaftliche Instanzen an ihren formalen Operationen Arbeiten, um sie nicht nur im Sinne der Stärkung der eigenen Position in der Gesellschaft zu verbessern, sondern auch im Sinne der Förderung des Lebenslaufs ihrer Adressaten bzw. der Zuverlässigkeit von (positiven wie negativen) Sanktionsoperationen an der Wurzel der (Um)Verteilung von Akteuren auf gesellschaftliche Tätigkeiten, entsprechende Bereiche und dort aktive Instanzen. Aus einem solchen Ansatz ziehen wir zwei wichtigen Botschaften.

Die erste Botschaft betrifft den gesellschaftlichen Zusammenhalt. Der gesellschaftliche Zusammenhalt ist kein Zustand, sondern eine Dynamik [cite:@sackmann98:_konkur_gener_arbeit, 82], die eine eigene Elastizität je nachdem hat, wie gut oder weniger gut die Lebensläufe durch die Einbettung von Akteuren und gesellschaftlichen Instanzen strukturiert werden. In seinem Ansatz denkt Sackmann eine solche Dynamik mit dem Begriff der Figuration von Norbert Elias, vom dem er insbesondere die Interdependenz der protagonistischen und antagonistischen Akteuren in Figurationen sowie die Machtbalancen hervorhebt (ebd., bes. 73ff.). Figurationen sind keine Zustände, sondern Zusammenstellungen von Einzel- wie Kollektiveakteuren und Nicht-Akteuren, die sich in Zeit und Raum mehr oder weniger verbreiten oder schrumpfen. Die zweite Botschaft betrifft diese Verbreitung bzw. Schrumpfung. Im Rahmen von Figuration denkt sie Elias als von Machtbalancen innerhalb von Figuration sowie von den Machtbalancen zwischen Figurationen abhängig, was bedeutet, dass (Kollektiv)Akteure in Figuration "nicht gleich stark" sind (ebd. 75), weshalb auch Asymmetrien entstehen, die jedoch keine radikalen Asymmetrien im Sinne der Monopolisierung von Macht bilden: "selten gelingt es einer Konfliktpartei, die andere vollkommen zu entmachten" (ebd.). Die Macht wird in Figurationen eng mit der Interdependenz von den unterschiedlichen (Kollektiv)Akteuren verbunden und somit dynamisiert, was im Begriff "Balance" wiedergegeben wird -- die Macht ist im Wechselspiel der (Kollektiv)Akteuren eingebettet und wird im Laufe der Strukturierung der Lebensläufe von Einzelakteuren und der Position von gesellschaftlichen Instanzen mitstrukturiert. Einmal figurationssoziologisch aufgefasst, erscheinen Lebensläufe von Einzelakteuren und Generationen von Akteuren nicht mehr als individuelle Mikrophänomene "neben" der Gesellschaft als Makrophänomen, sondern eine solche Unterscheidung ist überflüssig, weil sie durch ein prozedurales Verständnis von Figurationen als Einbettungs- bzw. Einschreibungskontexte von unterschiedlichen gesellschaftlichen Dimensionen ersetzt wird. Ein solcher Ansatz führt dann zur analytischen folgenden Frage: Was haben wir für Figurationen in unseren Gesellschaft mit welchen Folgen für die Handlung in dieser Gesellschaft und schließlich für diese Gesellschaft selbst?

Eine solche Frage teilen wir in einem etwas anderen theoretischen Rahmen, den wir mit dem Versuch skizziert haben, eine Theorie der Relation anzubieten, die Relation nach einem Makroansatz definiert und entwickelt [cite:@papilloud22:_skizz_theor_relat]. Verglichen mit dem figurationssoziologischen Ansatz Sackmanns geht es in diesem Theorierahmen darum, die Einbettungszusammenhänge radikaler als Relationsstrukturen zu konzipieren, die Ordnungen von Verhältnissen mit (Kollektiv)Akteuren, Nicht-Akteuren und Medien darstellen, die sich nach einer spezifischen Dynamik entwickeln bzw. die verbreitet oder geschrumpft werden. Wichtig dabei bleibt der Ansatz, den wir im Rahmen Sackmanns Deutung der Figuration Elias' zusammengefasst haben: Relationsstrukturen stellen stratifizierte Einbettungs- bzw. Einschreibungskontexte von gesellschaftlichen Phänomenen, Akteuren und Kollektiven in der Form von Verhältnissen dar, die nach einer spezifischen Dynamik der Balance von all möglichen Verhältnissen strukturiert werden, was wiederum eine solche Dynamik strukturiert bzw. verbreitet, be- oder entschleunigt, schrumpfen lässt oder korrigiert. In einem solchen Rahmen bewegt sich die nachfolgende einführende Untersuchung vom Kollektivakteur Rechenzentren, mit der wir einen Beitrag zur Frage leisten wollen, welche Machtbalance Rechenzentren in unserer Gesellschaft in den Vordergrund bringen und welche Folgen entstehen daraus für weitere Ordnungen von Verhältnissen. Als erster Schritt in dieser Untersuchung wollen wir verstehen, was Rechenzentren für eine Art von gesellschaftlicher Instanz sind.

* Rechenzentren in Deutschland. Eine Verortung

Ein erstes Problem, das den Rahmen der Theorie der Relation lösen will, betrifft die Diskrepanz zwischen dem Realen und dem Formalen bei der Verortung von Instanzen der Gesellschaft bzw. bei der Beschreibung der Position von gesellschaftlichen Instanzen in Ordnungen von Verhältnissen. Real können wir Instanzen und Instanzfraktionen möglicherweise in unterschiedlichen Orten der Gesellschaft finden. Nehmen wir das Beispiel der Forschung: Sie kann als akademische Forschung im Rahmen von Hochschulen oder von Forschungszentren stattfinden, aber sie kann auch in Abteilungen von Industrien oder Firmen sowie auch im Rahmen der Politikberatung oder des Journalismus praktisiert werden. Strukturell setzt sie gleiche Rahmenbedingungen überall in Bezug auf die Mittel sowie auf die Zwecken voraus: einen Zugang zu einer zuverlässigen Information, die bei Bedarf durch Einbezug von weiteren Akteuren, Kollektiven, Nicht-Akteuren und Medien kontrolliert und vertieft wird, die verarbeitet eine breite oder weniger breit Öffentlichkeit erreicht. Forschung kann folglich überall in der Gesellschaft auftauchen. Aber nicht überall in dieser Gesellschaft ist Forschung gleich Forschung, sondern es hängt davon ab, sagen wir im Rahmen der Theorie der Relation, welche Ordnung von Verhältnisse Forschung einerseits strukturiert und Forschung andererseits unterstützt. Damit wird verstanden, dass die Forschung an Universitäten im Vergleich etwa zur Forschung in Firmen nicht besser/schlechter, wichtiger/weniger wichtig, schneller/langsamer, stärker/schwächer wäre, sondern Verhältnisse zwischen Akteuren, Instanzen, Nicht-Akteuren und Medien in der Forschung anders gestaltet bzw. eine andere Relationalität oder relationale Dynamik zwischen ihnen entwickelt.

Im Rahmen der Theorie der Relation haben wir versucht, diesen Ansatz in seinen letzten Folgen zu denken. Daraus ergibt sich, dass die relationale Dynamik einer Ordnung von Verhältnissen als Leitbild für die Entwicklung der gesellschaftlichen Zirkulation von Akteuren und die Positionierung bzw. Verortung von gesellschaftlichen Instanzen funktioniert, die sie beeinflussen. Weiter haben wir nahegelegt, dass eine Ordnung von Verhältnissen die anderen Ordnungen von Verhältnissen über ihre eigenen Instanzen nach ihrer eigenen Dynamik zu beeinflussen versucht, um sich auf die anderen Ordnungen von Verhältnissen so zu verbreiten, als ob diese anderen Ordnungen von Verhältnissen Merkmale ihrer Dynamik wären. Im Zusammenhang dieses Beitrages wollen wir die zwei Anhaltspunkte dieser Überlegung miteinander enger verbinden, indem wir ausgehend von der Verortung der Rechenzentren in Ordnungen von Verhältnissen zeigen, wie sie andere Ordnungen von Verhältnissen zu beeinflussen beabsichtigen und auf welche Schwierigkeiten sie treffen.

Es kann zuerst überraschen, dass wir die Rechenzentren nicht unmittelbar in der medialen Umwelt der Gesellschaft ansiedeln oder, in den Begriffen der Theorie der Relation, dass wir sie nicht a priori als Instanzen einer medialen Ordnung von Verhältnissen bzw. einer medialen Relationsstruktur identifizieren. Dies hat zwei komplementäre Gründen. Der erste Grund ergibt sich aus dem Beispiel, das wir oben erwähnt haben, wenn wir von der Forschung gesprochen haben: Rechenzentren sind nicht gleich Rechenzentren je nach dem Bereich der Gesellschaft, den wir uns anschauen bzw. je nach der Einbettung von Verhältnissen, davon sie einerseits ein Ergebnis sind und deren Entwicklung sie unterstützen, wenn sie existieren. Diese Anmerkung erlaubt eine weitere Einschränkung vom Thema dieses Beitrags, der die Rechenzentren fokussiert, die als Instanz der medialen Relationsstruktur gelten. Im Ansatz der Theorie der Relation werden solche Instanzen deshalb spezifisch, weil sie an der Optimierung der Attraktivität von Medien in allen Formen von Verhältnissen arbeiten. Diese Arbeit setzt eine Beschäftigung mit den materiellen Bedingungen von solchen medialen Verhältnissen voraus, die darauf abzielt, die Investition in solche Verhältnisse zu vermehren und die Mobilisierung von solchen Verhältnissen in der Gesellschaft zu intensivieren. Das endgültige Ziel von einer solchen Arbeit ist, dass solche medialen Verhältnisse und deren entsprechenden Media in der Gesellschaft an Repräsentation und Legitimität als diese Verhältnisse und Medien gewinnen, die möglicherweise in der ganzen Gesellschaft verbreitet und andere Verhältnisse nach diesem Muster strukturieren werden. Mit diesen ersten Grund kommt einen zweiten Grund zusammen, der sich nicht aus unserem theortischen Ansatz ergibt, sondern er entsteht aus der Literatur zu den Rechenzentren.

Ein Blick in die Literatur zu Rechenzentren zeigt, dass Rechenzentren selten Gegenstände der soziologischen Untersuchung gewesen sind. Wenn man den Blick auf die sozialwissenschaftliche Literatur erweitert, dann merkt man, dass Rechenzentren insbesondere in Verbindung mit einem Ansatz untersucht werden, der auf die materiellen Grundlagen von Rechenoperationen zurückgreift und dabei die Botschaft liefert, dass die abstrakte bzw. virtuelle Welt der Informationsgesellschaft viele konkrete Elemente voraussetzt, ohne die sie gar nicht existieren könnte [cite:vgl. etwa @blanchette11:_mater_histor_bits;@mattern13:_code_clay_data_dirt;@parks15:_signal_traff;@starosielski15:_under_networ]. In dieser Hinsicht sind Rechenzentren für eine Gesellschaft, die sich wie unsere Gesellschaften als Informationsgesellschaft entwickelt, so wichtig wie der Keller im Haus: Er muss stehen, damit das Haus nicht zusammenstürzt. Dieser Ansatz ist nicht nur wichtig für die sozialwissenschaftliche Literatur geworden, die sich seit der letzten Dekade mehr mit infrastrukturellen Bedingungen der Informationsgesellschaft beschäftigt. Sie fungiert auch als Kernmerkmal der Definition von Rechenzentren in der Expertenliteratur, die sich speziell mit den Rechenzentren als Zusammenstellung von unterschiedlichen Techniken und Kern der Informations- und Kommunikationstechnologien (IKT) auseinandersetzt.

** Erster Schritt: Definieren

Verortungen kann man ab der Arbeit am Selbstverständnis


Die Rechenzentren haben nach wie vor folgende Probleme:

*** Ausdruck der Materialität:

Bau und Gebäude sind sehr wichtig, deshalb die Räumlichkeit in diesem Zusammenhang eine große Rolle spielt, die mit den ersten Studien zu Rechenzentren als erstes Kriterium für die Definition der Rechenzentren verwendet wird.

Am Anfang in der Entwicklung von Rechenzentren sieht man sie außerhalb von Großstädten angesiedelt, weil die Preise für Errichtung von Gebäuden weniger hoch sind. Das ist die Zeit der Entwicklung von kleinen Rechenzentren für die spezifischen Bedürfnissen von Firmen. Diese Rechenzentren kommunizieren nicht miteinander, sondern sie stehen nebeneinander im Raum.

Mit der Entwicklung von Internet in den 1990er Jahre und die Entstehung von Machtakteure der Medienbranche in den Städten geht ein dreifaches Trend a) der Verbindung zwischen den besonderen Rechenzentren über das Internet, b) der Teilung von Räumlichkeiten innerhalb von Rechenzentren und b) der Errichtung von Rechenzentren in Großstädten, in denen die Machtakteure der Medienbranche angesiedelt sind.

Mit der weiteren Entwicklung von Internet und digitalen Kommunikationen in der Form von sozialen Netzwerken und vom cloud computing ab der Jahre 2000 geht ein weiteres dreifaches Trend a) der Vergrößerung der Räumlichkeiten von Rechenzentren, die deshalb in industriellen Vierteln von Großstädten aufgebaut werden, wo größere Flächen verfügbar sind b) des Mehrbedarfs an Strom, um die Rechenzentren zu versorgen, der von der c) technologischen Entwicklung der rechnerischen Kapazitäten von Servern verursacht wird, die u.a. durch die Verschiebung der Rechenkapazität von CPU auf GPU deutlich beschleunigt wird (mehr Berechnungen per Sekunde), was mehr Strom verlangt.

*** Ausdruck der Schnittstelle mit Wissen:

An diesem Punkt erreicht man die Schnittstelle zwischen dem materiellen Bedarf von Rechenzentren und die Mehrinvestition in die Technik selbst. Hier auch ist diese Mehrinvestition immer im Hintergrund der Errichtung von Gebäuden für Rechenzentren anwesend, weil Rechenzentren spezielle Gebäudetechniken verlangen, um Pannen zu vermeiden (Abkühlung von Räumlichkeiten, Isolierung gegen Feuchtigkeit, Bodentechnik um Bodenstürtze zu vermeiden). Dieser Punkt gewinnt an Bedeutung mit der technischen Entwicklung von Rechenzentren, die ein qualifiziertes Personal verlangen, das im Fall von Pannen intervenieren kann. Wenn am Anfang der Entwicklung von Rechenzentren insbesondere Personal aus dem Bausektor als wichtig für die Gebäudetechnik erscheinen, werden mit der Entwicklung der Rechentechnik Techniker und Ingenieure wichtig.

Das über wirtschaftliche Sektoren ebenfalls wissenschaftliche Einrichtungen für die Errichtung und das Funktionieren von Rechenzentren mit einbezogen werden müssen, führt zur Vorstellung, dass Rechenzentren neue wirtschaftliche Märkte eröffnen und einen konkreten Schritt ein eine reale wissensbasierte Wirtschaft leisten. In diesem Zusammenhang wird insbesondere von der Politik erwartet, dass Rechenzentren Arbeit schaffen werden und somit einen bedeutsamen Beitrag zum wirtschaftlichen Wachstum leisten werden. An der Seite der Politik wird erwartet, dass 1 Job im Rahmen von Rechenzentren bis 7.5 in der lokalen bzw. regionalen Wirtschaft kreiert. Selbst heute spricht Donald Trump von der Beschaffung von 100.000 Arbeitsplätzen durch neue Rechenzentren.

Für die Machtakteure der Medien, die mittelbar und unmittelbar mit dem Aufbau von Rechenzentren beschäftigt sind, muss diese politische Erwartung einbezogen werden, damit sie von der Investition öffentlicher Gelder zur Konsolidierung ihrer Einflussstrategie in der Gesellschaft profitieren können. Aber es ist kompliziert.

*** Ausdruck Machtbalance bzw. Abweichung von der Satellisierung der Wirtschaft, der Wissenschaft und der Politik:

Das erste Problem betrifft den Kernelement vom Selbstverständnis der Machtakteure der Medien, die, wenn sie ihren Einfluss auf die ganze Gesellschaft ausüben wollen, ihre Einflussstrategie unaufhörlich entwickeln müssen. Auf der Ebene von Rechenzentren bedeutet dies, dass solche Rechenzentren ständig funktionieren müssen, auch wenn sie immer größer und in ihrer Verwaltung und Wartung komplizierter werden. Da Rechenzentren Pannen erleben, muss nicht nur die Technik häufig verdoppelt werden, sondern auch die Techniker müssen gefunden werden, die Pannen reparieren können. Mit der raschen technologischen Entwicklung von Serverelementen wie GPU-Chips sind Techniker, die mit diesen neuen Technologien umgehen können, weniger geworden, weil Ausbildungen in diesem Bereich noch nicht existieren bzw. von Hochschulen angeboten werden. Deshalb müssen Machtakteure der Medien nicht nur dafür sorgen, dass die letzte Technologie in ihre Rechenzentren gehen, sondern sie müssen auch dafür sorgen, dass ein kompetentes Personal gefunden wird, das diese Zentren verwalten und warten können.

In diesem Zusammenhang hat man eine Balance der Macht von Machtakteuren der Medien, die daher kommt, dass die Entwicklung von ihrem Einflussstrategie auf die Gesellschaft nicht gestaltet werden kann, wie sie es sich wünschen, was dann komplizierter macht, die Politik davon zu überzeugen, dass es mit öffentlichen Geldern in ihren Rechenzentren investiert werden sollte. Manche von diesen Akteuren wie etwa Mark Zuckerberg von Meta greifen dann in die eigene Gelder, um eigene Rechenzentren zu errichten, die dann mit der eigenen Infrastrukturen an Personal und Energieversorgung funktionieren sollten. Hier sieht man ein Beispiel, wie ein Akteur in einer Figuration versucht, die Machtbalance zwischen den Akteuren zu beeinflussen, um mehr macht beim Einfluss der anderen Akteuren in dieser Figuration sowie mittelbar auch in den anderen Figuration zu beeinflussen.

*** Zurück zur Machtbalance:

Wie sie von Elias konzipiert wird (Beispiel Fussball), ist die Machtbalance dadurch verursacht, dass Gegenakteure die Handlung von Akteuren ausbremsen bzw. einschränken, die sich in der gleichen Figuration mit den Akteuren befinden, dagegen sie kämpfen. In der Theorie der Relation entspricht diese Auffassung von Machtbalance eine Blockadestrategie im Sinne einer klaren Verteidigung von der eigenen Ordnung von Verhältnissen auf der Grundlage der Aufbewahrung der eigenen Legitimität bzw. des eigenen Selbstverständnis. Mit diesem Beispiel der Rechenzentren sieht man, dass Elias' Auffassung von Machtbalance eine grundsätzlichere Vorstellung von Macht voraussetzt, die im Rahmen des Figurationsansatzes von Elias nicht in ihren Folgen thematisiert wird: die Macht durch Allianzen. Um das Beispiel des Fussballs wieder zu erwähnen, kann man sagen, dass Fussballmanschaften andere Fussballmanschaften brauchen, um ihre sportliche Leistungen bzw. ihre Techniken, Taktiken und Strategien zu verbessern, die weniger als "Gegener" wahrgenommen werden, sondern mehr als "Partner" im Rahmen von einem strukturierten Wettbewerb gelten, die erlauben, an der Optimierung der eignen Organisation des Spieles zu arbeiten, um sie möglicherweise langfristig zu steigern. Dass am Ende eine Mannschaft das Pokal gewinnt, ist für die Attraktivität dieser Mannschaft gut, aber es ist insgesamt weniger als die langfristige Steigerung der eigenen Optimierung wichtig. Oder anders gesagt: Einmal zu gewinnen ist gut, regelmäßig zu gewinnen ist besser. Damit gewinnt man an Einfluss auf die anderen Mannschaften im Sinne der Spielorganisation und der Spieler in dieser Organisation, wie man insgesamt an Attraktivität für weitere Akteure innerhalb und außerhalb der Fußballbranche gewinnt.

Relationsstrukturen versuchen, sich langfristig auf weitere Relationsstrukturen zu verbreiten, weshalb sie unaufhörlich an Allianzen als privilegierte Strategie der eigenen Verbreitung und der Steigerung der eigenen Legitimität und damit der eigenen Macht arbeiten.

*** Energieeinsparung als Rhetorik zur Optimierung des Selbstverständnisses von Machtakteuren der Medien:

Natur als Problem der Umverteilung von Ressourcen.



Lebensläufe werden entsprechend als relationale Komplexe konzeptualisiert, die Symbolen und formale Prozessen von gesellschaftlichen Instanz einbeziehen, davon strukturiert werden und sie ebenfalls strukturieren.

* Einleitung. Was passiert um die KI

Die Idee von dieser Arbeit ist aus den verschiedenen Gesprächen entstanden, die ich mit Kollegen zur Entwicklung der künstlichen Intelligenz (KI) durchgeführt habe, und die nach der Veröffentlichung vom Prognose "AI-2027" der Autoren Daniel Kokotajlo, Scott Alexander, Thomas Larsen, Eli Lifland und Romeo Dean an Brisanz gewonnen haben [cite:@ai-2027].
