#+Bibliography: /home/cpsoz/Github/rom/CP-ROM.bib

In dem vorliegenden Vorhaben wollen wir auf einen der wichtigsten Ansätze des soziologischen Denkens Reinhold Sackmanns zurückgreifen und ihn an einem Beispiel vertiefen und weiterentwickeln. Dieser Ansatz finden wir im Oeuvre Sackmanns unterschiedlich ausgedruckt, wie etwa in den Schlussfolgerungen seiner Habilitationsschrift, wenn er zur Lebenslaufsoziologie sagt: "An den Anfängen dieser Disziplin (...) stand die Vorstellung, daß Alter neben seiner biologischen Komponente auch gesellschaftlich kulturelle Elemente enthält. Gesellschaft war ein Nebenfaktor, der wahrgenommen werden sollte. In der Theorie des institutionalisierten Lebenslaufs gewann die Vorstellung Kontur, daß die modernen gesellschaftlichen Institutionen (...) spezifische Lebensläufe kontitutieren" [cite:@sackmann98:_konkur_gener_arbeit, 228-229]. Dabei legt Sackmann nah, dass sich die künftige Forschung in der Lebenslaufsoziologie mit der Art und Weise auseinandersetzen sollte, wie Lebensläufe als eingebettete Prozesse an der Schnittstelle der Biographien von Akteuren und der formalen Operationen von gesellschaftlichen Instanzen entstehen und von einer solchen Einbettung strukturiert werden. "Lebensläufe" sagt er in einem anderen Beitrag "vollziehen sich eingebettet, in Gruppen, in Gemeinschaften, Gesellschaften und v.a. Organisationen" [cite:@sackmann07:_leben_biogr, 206]. Lebensläufe werden entsprechend als relationale Komplexe konzeptualisiert, die Symbolen und formale Prozessen von gesellschaftlichen Instanz einbeziehen, davon strukturiert werden und sie ebenfalls strukturieren.

* Einleitung. Was passiert um die KI

Die Idee von dieser Arbeit ist aus den verschiedenen Gesprächen entstanden, die ich mit Kollegen zur Entwicklung der künstlichen Intelligenz (KI) durchgeführt habe, und die nach der Veröffentlichung vom Prognose "AI-2027" der Autoren Daniel Kokotajlo, Scott Alexander, Thomas Larsen, Eli Lifland und Romeo Dean an Brisanz gewonnen haben [cite:@ai-2027].
