#+Bibliography: /home/cpsoz/Github/rom/CP-ROM.bib

* Einleitung

Im Oeuvre Reinhold Sackmanns hat uns einen Ansatz besonders interessiert, den er im Rahmen seiner unterschiedlichen Arbeiten zur Demographie, zur Lebenslaufsoziologie und zu gesellschaftlichen Instanzen der Sozialisation wie den (Hoch)Schulen, dem Arbeitsmarkt oder dem Rentensystem entwickelt hat. Dieser Ansatz finden wir in seinen Arbeiten unterschiedlich ausgedruckt. Nehmen wir etwa die Schlussfolgerungen seiner Habilitationsschrift, wenn er eine Bilanz zur Lebenslaufsoziologie wie folgt zieht: "An den Anfängen dieser Disziplin (...) stand die Vorstellung, daß Alter neben seiner biologischen Komponente auch gesellschaftlich kulturelle Elemente enthält. Gesellschaft war ein Nebenfaktor, der wahrgenommen werden sollte. In der Theorie des institutionalisierten Lebenslaufs gewann die Vorstellung Kontur, daß die modernen gesellschaftlichen Institutionen (...) spezifische Lebensläufe kontitutieren" [cite:@sackmann98:_konkur_gener_arbeit, 228-229]. Dabei legt Sackmann nah, dass sich die künftige Forschung in der Lebenslaufsoziologie mit der Art und Weise auseinandersetzen sollte, wie Lebensläufe als eingebettete Prozesse an der Schnittstelle der Biographien von Akteuren und der formalen Operationen von gesellschaftlichen Instanzen entstehen und von einer solchen Einbettung strukturiert werden. "Lebensläufe", wie er in einem späteren Beitrag sagt, "vollziehen sich eingebettet, in Gruppen, in Gemeinschaften, Gesellschaften und v.a. Organisationen" [cite:@sackmann07:_leben_biogr, 206]. Dieser Ansatz ist aus den folgenden Gründen interessant.

Sackmann versteht Lebensläufe nicht mehr im geläufigen soziologischen Sinn von "trajectoires", die den Fokus auf den Weg der Akteure von gesellschaftlichen Instanzen der Sozialisation zu weiteren gesellschaftlichen Instanzen der Sozialisation setzen. Damit wird gesagt, das gesellschaftliche Sozialisationsinstanzen wie etwa (Hoch)Schulen oder Arbeitsmarkt mehr als nur "verpflichtende Anlaufstationen" von Akteuren sind [cite:@latour05:_reass_social], die Akteure registrieren würden und je nach Sozialisationserfolg unterschiedlich auf weitere gesellschaftliche Bahnen umverteilen würden. Gesellschaftliche Instanzen sind keine irreflexive Orte der Vergebung von Titeln und Rechten, sondern sie geben den Akteuren Einschreibungsmöglichkeiten in der Gesellschaft und reflektieren entsprechend über ihre Rolle in diesem Zusammenhang. Auch zu diesem Zweck entwickeln gesellschaftliche Instanzen dauernd formale Verfahren, die Orientierungsmuster bzw. "Leitbilder" für die Akteure schaffen und deshalb auf ihre Laufbahnen wirken [cite:@sackmann07:_leben_biogr, 206]. Dass eine solche Wirkung auch unintendierte Folgen hat und Ungleichheiten zwischen Akteuren bzw. Akteurgenerationen generiert, hat Sackmann mehrmals im Sinne einer kritischen soziologischen Betrachtung von gesellschaftlichen Instanzen unterstrichen [cite: vgl. etwa @sackmann15:_bedeut_auswah_erzeug_bildun; vgl. auch @sackmann19:_mechan_eliteb]. Aber eine kritische Betrachtung von gesellschaftlichen Instanzen reicht allein nicht aus. Nach Sackmann müssen ebenfalls Korrekturmaßnahmen von gesellschaftlichen Instanzen abgebildet werden, die darauf abzielen, Maßnahmen und entsprechende formale Verfahren zur Einschränkungen bzw. Schrumpfung der Ungleichheitsproduktion zu definieren.

Mit diesem konstruktiven Korrelat zur kritischen Betrachtung von gesellschaftlichen Instanzen bringt Sackmann seinen Ansatz zur Vollendung: Weil Kollektivakteure als Teil des Einschreibungskontextes fungieren, den sie mit den Akteuren aufbauen und innerhalb dessen die Laufbahn von solchen Akteuren strukturiert wird, ist es aus Sicht einer soziologischen Makroperspektive nicht ausreichend, nur die Defizite von Kollektivakteuren in ihren Wechselwirkungen mit Einzelakteuren hervorzuheben. Es muss ebenfalls verstanden werden, wie gesellschaftliche Instanzen an ihren formalen Operationen Arbeiten, um sie nicht nur im Sinne der Stärkung der eigenen Position in der Gesellschaft zu verbessern, sondern auch im Sinne der Förderung des Lebenslaufs ihrer Adressaten bzw. der Zuverlässigkeit von (positiven wie negativen) Sanktionsoperationen an der Wurzel der (Um)Verteilung von Akteuren auf gesellschaftliche Tätigkeiten, entsprechende Bereiche und dort aktive Instanzen. Aus einem solchen Ansatz erkennen wir zwei wichtigen Botschaften.

Die erste Botschaft betrifft den gesellschaftlichen Zusammenhalt. Der gesellschaftliche Zusammenhalt ist kein Zustand, sondern eine Dynamik [cite:@sackmann98:_konkur_gener_arbeit, 82], die eine eigene Elastizität je nachdem hat, wie gut oder weniger gut die Lebensläufe durch die Einbettung von Akteuren und gesellschaftlichen Instanzen strukturiert werden. In seinem Ansatz denkt Sackmann eine solche Dynamik mit dem Begriff der Figuration von Norbert Elias, von dem er insbesondere die Interdependenz der protagonistischen und antagonistischen Akteuren in Figurationen sowie die Machtbalancen hervorhebt (ebd., bes. 73ff.). Figurationen sind keine Zustände, sondern Zusammenstellungen von Einzel- wie Kollektiveakteuren und Nicht-Akteuren, die sich in Zeit und Raum mehr oder weniger verbreiten oder schrumpfen. Die zweite Botschaft betrifft diese Verbreitung bzw. Schrumpfung. Im Rahmen von Figuration denkt sie Elias als von Machtbalancen innerhalb von Figuration sowie von den Machtbalancen zwischen Figurationen abhängig, was bedeutet, dass (Kollektiv)Akteure in Figuration "nicht gleich stark" sind (ebd. 75), weshalb auch Asymmetrien entstehen, die jedoch keine radikalen Asymmetrien im Sinne der Monopolisierung von Macht bilden: "selten gelingt es einer Konfliktpartei, die andere vollkommen zu entmachten" (ebd.). Die Macht wird in Figurationen eng mit der Interdependenz von den unterschiedlichen (Kollektiv)Akteuren verbunden und somit dynamisiert, was im Begriff "Balance" wiedergegeben wird -- die Macht ist im Wechselspiel der (Kollektiv)Akteuren eingebettet und wird im Laufe der Strukturierung der Lebensläufe von Einzelakteuren und der Position von gesellschaftlichen Instanzen mitstrukturiert. Einmal figurationssoziologisch aufgefasst, erscheinen Lebensläufe von Einzelakteuren und Generationen von Akteuren nicht mehr als individuelle Mikrophänomene "neben" der Gesellschaft als Makrophänomen. Eine solche Unterscheidung kann zugunsten von einem prozeduralen Verständnis von Figurationen als Einbettungs- bzw. Einschreibungskontexte von unterschiedlichen gesellschaftlichen Dimensionen ersetzt werden. Damit stellt sich die folgende analytische Frage: Was haben wir für Figurationen in unserer Gesellschaft, und welche Folgen haben sie für die Handlung in dieser Gesellschaft und schließlich für diese Gesellschaft selbst?

Eine solche Frage teilen wir im Rahmen der Theorie der Relation, die Relation nach einem Makroansatz definiert und entwickelt [cite:@papilloud22:_skizz_theor_relat]. Verglichen mit dem figurationssoziologischen Ansatz Sackmanns geht es in diesem Theorierahmen darum, die Einbettungszusammenhänge radikaler als Relationsstrukturen zu konzipieren, die Ordnungen von Verhältnissen mit (Kollektiv)Akteuren, Nicht-Akteuren und Medien darstellen, die sich nach einer spezifischen Dynamik entwickeln bzw. die verbreitet oder geschrumpft werden. Wichtig dabei bleibt der Ansatz, den wir im Rahmen Sackmanns Deutung der Figuration Elias' zusammengefasst haben: Relationsstrukturen stellen stratifizierte Einbettungs- bzw. Einschreibungskontexte von gesellschaftlichen Phänomenen, Akteuren und Kollektiven in der Form von Verhältnissen dar, die nach einer spezifischen Dynamik der Balance von all möglichen Verhältnissen strukturiert werden, was wiederum eine solche Dynamik strukturiert bzw. verbreitet, be- oder entschleunigt, schrumpfen lässt oder korrigiert. In einem solchen Rahmen bewegt sich die nachfolgende einführende Untersuchung vom Kollektivakteur Rechenzentren, mit der wir einen Beitrag zur Frage leisten wollen, welche Machtbalance Rechenzentren in unserer Gesellschaft in den Vordergrund bringen und welche Folgen entstehen daraus für weitere Ordnungen von Verhältnissen. Als erster Schritt in dieser Untersuchung wollen wir verstehen, was Rechenzentren für eine Art von gesellschaftlicher Instanz sind.

* Rechenzentren verorten

Ein erstes Problem, das den Rahmen der Theorie der Relation lösen will, betrifft die Diskrepanz zwischen dem Realen und dem Formalen bei der Verortung von Instanzen der Gesellschaft bzw. bei der Beschreibung der Position von gesellschaftlichen Instanzen in Ordnungen von Verhältnissen. Real können wir Instanzen und Instanzfraktionen in unterschiedlichen Orten der Gesellschaft finden. Nehmen wir das Beispiel der Forschung: Sie kann als akademische Forschung im Rahmen von Hochschulen oder von Forschungszentren stattfinden, aber sie kann auch in Abteilungen von Industrien oder Firmen sowie auch im Rahmen der Politikberatung oder des Journalismus praktisiert werden. Strukturell setzt sie gleiche Rahmenbedingungen überall in Bezug auf die Mittel sowie auf die Zwecken der Forschung voraus: einen Zugang zu einer zuverlässigen Information, die durch Einbezug von weiteren Akteuren, Kollektiven, Nicht-Akteuren und Medien kontrolliert und vertieft werden kann und eine breite oder weniger breit Öffentlichkeit erreichen muss. Forschung kann folglich überall in der Gesellschaft auftauchen. Aber nicht überall in dieser Gesellschaft ist Forschung gleich Forschung, sondern es hängt davon ab, welche Ordnung von Verhältnisse Forschung einerseits strukturiert und Forschung andererseits unterstützt. Damit wird verstanden, dass die Forschung an Universitäten im Vergleich etwa zur Forschung in Firmen nicht besser/schlechter, wichtiger/weniger wichtig, schneller/langsamer, stärker/schwächer wäre, sondern Verhältnisse zwischen Akteuren, Instanzen, Nicht-Akteuren und Medien in der Forschung anders gestaltet bzw. eine andere Relationalität oder relationale Dynamik zwischen ihnen entwickelt. Daraus ergibt sich, dass die relationale Dynamik einer Ordnung von Verhältnissen als Leitbild für die Entwicklung der gesellschaftlichen Zirkulation von Akteuren und die Positionierung bzw. Verortung von gesellschaftlichen Instanzen funktioniert und ihre Handlung entsprechend beeinflusst. Diese Überlegung kann gleichermaßen zwischen Ordnungen von Verhältnissen bzw. Relationsstrukturen entwickelt werden: eine Ordnung von Verhältnissen versucht stets, die anderen Ordnungen von Verhältnissen über ihre eigenen Instanzen nach ihrer eigenen Dynamik zu beeinflussen, um sich auf die anderen Ordnungen von Verhältnissen so zu verbreiten, als ob diese anderen Ordnungen von Verhältnissen Merkmale ihrer Dynamik wären. Im Zusammenhang dieses Beitrages wollen wir die zwei Anhaltspunkte dieser Überlegung miteinander enger verbinden, indem wir ausgehend von der Verortung der Rechenzentren in Ordnungen von Verhältnissen zeigen, wie sie andere Ordnungen von Verhältnissen zu beeinflussen beabsichtigen und auf welche Schwierigkeiten sie treffen.

Aus unserer Ausführung am Beispiel der Forschung kann schlussfolgert werden, dass Rechenzentren nicht zwangsläufig in der medialen Umwelt der Gesellschaft angesiedelt werden oder, in den Begriffen der Theorie der Relation, dass wir sie nicht a priori als Instanzen einer medialen Ordnung von Verhältnissen bzw. einer medialen Relationsstruktur identifizieren. Rechenzentren sind nicht gleich Rechenzentren je nach dem Bereich der Gesellschaft, den wir uns anschauen bzw. je nach der Einbettung von Verhältnissen, davon sie einerseits ein Ergebnis sind und deren Entwicklung sie unterstützen. Diese Anmerkung führt zur weiteren Einschränkung von unserem Thema: Wir fokussieren die Rechenzentren, die als Instanz der medialen Relationsstruktur gelten. Nach dem Ansatz der Theorie der Relation sind solche Instanzen diejenige, die an der Optimierung der Attraktivität von Medien in allen Formen von Verhältnissen und deshalb an der Optimierung von solchen medialen Verhältnissen arbeiten. Diese Arbeit setzt eine Beschäftigung mit den materiellen Bedingungen von solchen medialen Verhältnissen voraus, um die Investition in solche Verhältnisse zu vermehren und die Mobilisierung von solchen Verhältnissen in der Gesellschaft zu intensivieren. So kann die Repräsentation von solchen medialen Verhältnissen und deren entsprechenden Media in der Gesellschaft sowie ihre Legitimität als diese Verhältnisse und Medien gestärkt werden, die möglicherweise in der ganzen Gesellschaft verbreitet und andere Verhältnisse nach diesem Muster strukturieren werden.

Die erste Bedingung zur Verortung von Rechenzentren in der medialen Relationsstruktur ist in der Literatur zu den Rechenzentren gut abgebildet, selbst wenn hier die Literatur differenziert betrachtet werden muss. Sucht man nach wissenschaftlichen Beiträgen zu Rechenzentren als Gegenstände der soziologischen bzw. sozialwissenschaftlichen Untersuchung, dann merkt man dass Rechenzentren in Verbindung mit einem Ansatz untersucht werden, der auf die materiellen Grundlagen von Rechenoperationen zurückgreift. Dabei wird die Botschaft geliefert, dass die abstrakte bzw. virtuelle Welt der Informationsgesellschaft viele konkrete Elemente voraussetzt, ohne die sie gar nicht existieren könnte [cite:vgl. etwa @blanchette11:_mater_histor_bits;@mattern13:_code_clay_data_dirt;@parks15:_signal_traff;@starosielski15:_under_networ]. Wenn dieser Ansatz erst seit der letzten Dekade in den Sozialwissenschaften aufgegriffen wird, die sich vermehrt mit infrastrukturellen Bedingungen der Informationsgesellschaft beschäftigen, ruht er auf einer Fülle von Beiträgen aus der Literatur in den Bereichen der Technikwissenschaften (Ingenieurwissenschaft, Informatik, Physik), die sich speziell mit den Rechenzentren als Zusammenstellung von unterschiedlichen Techniken und als Kern der Informations- und Kommunikationstechnologien (IKT) auseinandersetzt. In diesen Bereichen sind materielle Bedingungen der Informationsgesellschaft von wichtiger Bedeutung nicht zufällig, sondern aufgrund der Orientierung dieser Bereiche an der Optimierung von Raum nicht im klassischen Sinne der geographischen Fläche, sondern zuerst im Sinne der Miniaturisierung von technischen Komponenten und im Allgemeinen von Medien. In vergangenen Arbeiten haben wir Untersuchungen zu diesem Ansatz vorgelegt, der nach dem Zweiten Weltkrieg im Rahmen der Entstehung von interaktiven Medien und der Entwicklung von Nanotechnologien in Verbindung mit unterschiedlichen Branchen der Wirtschaft (Kommunikationstechnologien, Lebensmittel) und Disziplinen der Wissenschaft (Medizin) entwickelt wird [cite:@monoPapilloud2007;@monoPapilloud2012;@kapitelPapilloud2013;@monoPapilloudSchultze2023]. Dabei handelt es sich darum, neue Räumlichkeiten durch die Miniaturisierung von materiellen Oberflächen für entsprechende miniaturisierten Technologien zu schaffen, die dann auf diesen Oberflächen vermehrt werden könnten. Insbesondere im Zusammenhang der Nanotechnologien versprechen Autoren eine neue industrielle Revolution durch eine solche radikale Miniaturisierung von Technologien, die mit sich eine Umverteilung von Räumlichkeiten bringt. Was da draußen als Raum beobachtet werden kann, wird dank der Eroberung von Räumlichkeiten innerhalb von Materien erspart. Mit diesem Ansatz ist der spezielle Ansatz, der den Diskurs der Expertenliteratur zu Rechenzentren strukturiert, eng verbunden. Er besagt, dass die Umverteilung von Räumlichkeiten zu einer Umverteilung von Energieressourcen führt: Wenn mehr Raum innerhalb von Materien für Technologien gefunden werden kann, dann können Technologien vermehrt werden, ohne mehr Räumlichkeiten in der Welt zu beanspruchen und ohne entsprechende zusätzliche Energieressourcen zu verlangen. Mehr (Technologien) führt zu weniger (Raum- und Energieverbrauch), was als eine negative Formulierung vom Mythos der Abundanz verstanden werden kann. Dieser speziellen Ansatz wird in der Literatur zu Rechenzentren immer bedeutsamer, wenn es verstanden wird, dass Rechenzentren den Kern von IKT und damit von der Informationsgesellschaft bilden.

* Rechenzentren als Kern der Informationsgesellschaft

Dass Rechenzentren den Kern der Informationsgesellschaft bilden, ist im Laufe der Zeit eine Selbstverständlichkeit geworden, die damals in der Gesellschaft vor dem Internet keine war. Die Arbeiten von Bernard Aebischer (ETH-Zürich) im Rahmen des /Centre for Energy Policy and Economics/ liefern in dieser Hinsicht wertvolle Quellen zur Rekonstruktion dieser Entwicklung. Aebischer arbeitet nicht speziell zu Rechenzentren, sondern er untersucht das breite Spektrum der IKT in historischer transnationaler Perspektive mit einem Modellierungsansatz. Aus dieser Arbeit gewinnt man eine Periodisierung der Entwicklung von IKT und eine Zeitspanne, ab der Rechenzentren immer mehr an Bedeutung für die Informationsgesellschaft gewinnen werden. Maßnahmen zur Einsparung von Energie werden unmittelbar nach den zwei Ölkrisen von 1973 und 1979 international eingeleitet [cite:@aebischer14:_energ_deman_ict, 6]. Strom wird teuer, deshalb wollen die Länder wissen, wie sie Strom sparen können. Im Laufe der 80er Jahre werden Rechner in der Form von /Personal Computer/ vermehrt in der Wirtschaft und in der Wissenschaft verwendet, was die ersten Studien zum Energieverbrauch von Rechnern in der Gesellschaft motiviert (ebd., 4). Diese Studien arbeiten mit einem Technologieansatz, der vom Moores Gesetz beeinflusst wird, nach dem die Anzahl an Transistoren in integrierten Schaltkreisen jede zwei Jahre verdoppelt wird (ebd.). Deshalb kommen sie zu vergleichbaren Ergebnissen. Der Energieverbrauch in der Gesellschaft steigt durch die vermehrte Verwendung von Rechnern. Aber mit der technologischen Entwicklung soll er schnell wieder senken. Simulationen und Szenarien, die in dieser Zeit von 1980 und 1990 für eine Zeitspanne von bis 40 Jahren gebildet werden (1985-2025), kommen zum Schluss, dass es gute Chancen gibt, dass in 2025 Rechner insgesamt nicht mehr Energie als im Jahr 1985 verbrauchen würden (etwa am Beispiel der Schweiz, ebd.). Dabei werden auch sog. /mainframes/ bzw. existierende Rechenzentren mitberücksichtigt, selbst wenn sie keine spezielle Hervorhebungen bekommen. Wie Aebischer unterstreicht, sind wir in einer Gesellschaft vor dem Internet: "the financial sector, research institutions and universities, a few industries and some governmental agencies were the only important users of large computers. Electricity demand of these machines was a concern for these organizations but was barely registered by policy makers or the general public" (ebd., 11). Um genauer zu wissen, was Aebischer mit "barely registered by policy makers" meint, können wir das Beispiel Deutschland heranziehen. Dieses Beispiel hat den zusätzlichen Vorteil, dass es auf einen methodologischen Ansatz bei Sackmann zurückgreift, der eine Integration von qualitativer und quantitativer Forschung auf der Grundlage von Topic-Modellen vorsieht, daran Sackmann u.a. auch mit unserer Anwendung /MTA/ bildet [cite:@sackmann20:_sozial_zusam_pandem;@papilloud17:_mta_multi_text_analy].

In der Zwischenzeit ist diese Methode in den Sozialwissenschaften rezipiert worden, weshalb wir sie hier nicht nochmal darstellen werden [cite:vlg. stattdessen @papilloud18:_einfü_analy_texten_topic_model]. Den methodologischen Zusammenhang wollen wir dennoch kurz präzisieren, in dem wir die folgende Topic-Modellierung verwendet haben, weil dieser Zusammenhang in unserem Fach unterbelichtet bleibt. Wir haben diese Modellierung im Rahmen von Workflows hergestellt, die dem Ansatz vom /literate programming/ folgen, nach dem Anwendungen so geschrieben werden, damit sie jeder Mensch versteht. In der Praxis bedeutet dies, dass ein Text (ein Bericht, ein Aufsatz, ein Buchkapitel usw.) geschrieben wird, der die methodologischen bzw. technischen Elementen enthält (wie etwa den Code für die Ausführung von unterschiedlichen Anwendung zur Herstellung von Statistiken, Tabellen, Graphiken usw.), die im Rahmen von diesem Text verwendet werden. Ein solcher Text bzw. eine solche Textdatei kann anschließend nicht nur als Bericht/Aufsatz, sondern auch als Anwendung benutzt werden. Sie kann ausgeführt werden, und dabei führt sie weitere Anwendungen aus, die für die Ausführung des Codes in der Datei notwendig sind. Damit sichert man eine vollständige Transparenz und Reproduzierbarkeit der unterschiedlichen Stufen, die zu einem Ergebnis geführt haben, das der Text veröffentlicht. Im Rahmen von solchen Workflows harmonieren qualitative sowie quantitative Daten im Dienst der wissenschaftlichen Untersuchung, dass eine Textdatei repräsentiert und aufgrund ihres Formates als Textdatei überall entweder als reine Textdatei oder als Anwendung verwendbar ist.

In dem Kontext dieses Vorhabens haben wir als Grundlage der Untersuchung zur Frage der Aufmerksamkeit von Politik in Deutschland auf die Fragen, die Rechenzentren stellen, die Parlamentsdokumente der Bundesrepublik Deutschland und die Protokollen des Bundestages herangezogen. Diese Dokumente können an der folgenden Adresse als XML-Dateien, mit einer API oder nach handwerklicher Suche heruntergeladen werden: https://www.bundestag.de/services/opendata. Ein Github-Konto bietet diesen Datensatz als R-Objekt an: https://github.com/benjaminguinaudeau/tidybundestag. Inhaltlich liefern diese Dokumente unterschiedliche Informationen zu den politischen Entscheidungen, die von 1949 bis heute auf Bundesebene getroffen werden. Bezogen auf das Thema des Vorhabens in dieser Arbeit erlauben sie eine Rekonstruktion der thematischen Zusammenhänge, in denen die Rechenzentren in Deutschland von der Politik wahrgenommen wurden. Wir haben uns auf die XML-Dateien bezogen, die wir in Textdateien umgewandelt haben. Wir haben diese Dateien mit den letzten Parlamentsdokumenten und Protokollen (bis Juni 2025) vervollständigt. Anschließend haben wir die Dokumente nach Wahlperioden klassifiziert, selektiert und nach Datum, Sprecher, politischer Partei vom Sprecher und politischem Status des Sprechers (etwa Ministerpräsidenten) zerlegt. Bei der Selektion sind wir zuerst mit einem breiten Ansatz vorgegangen, nach dem wenn das Wort "Rechenzentr" zumindest einmal in einem ganzen Dokument erscheint, dann dieses Dokument in die Analyse einfließt. Weil wir mit diesem Ansatz sehr viele Dokumente generiert haben, die mit dem Thema Rechenzentrum lose verbunden waren, haben wir den Ansatz enger gefasst und nur die Teile von Dokumenten bzw. die einzelnen Wortmeldungen von Sprechern ausgewählt, die sich unmittelbar mit dem Thema der Rechenzentren beschäftigt haben. Mit diesem letzten Ansatz konnten wir eine verdichtete Abbildung der Entwicklung der Themen zum Oberthema "Rechenzentrum" im Bundestag in der Zeit erhalten [[fig:Abb. 1]].

#+CAPTION: Entwicklung der Themen zum Oberthema "Rechenzentrum" im Bundestag
#+NAME: fig:Abb. 1
[[./Trends7T.pdf]]

Die Abbildung 1 zeigt einerseits, dass die Debatten im Bundestag das Thema Rechenzentren aus verschiedenen Perspektiven behandeln, die in der Zeit unterschiedlich bedeutsam sind. In Bezug auf die Aussage von Aebischer kann gesagt werden, dass die Politik in Deutschland auf Rechenzentren schon aufmerksam war. Aber wenn wir das Thema Energie fokussieren, sieht man dann, dass es nur im Themenkomplex Energie, Wirtschaft, Optimierung, Nachhaltigkeit behandelt wird und nur zwischen 1995 und 2000 ein Leitthema der Debatten im Bundestag gewesen ist. Davor steckt dieser Themenkomplex hinter dem Thema des Datenschutzes, und danach verliert es an Bedeutung im Vergleich zu den Themen der Forschung, der Wissenschaft und der Bildung sowie der Apotheken und der Medizin (in diesem Zusammenhang insbesondere in Bezug auf die Verbesserung der automatischen Verwaltung von Rechnungen und der entsprechenden Zahlung dieser Rechnungen). Am Ende der Zeitspanne herrschen insbesondere die Themen der nationalen Verteidigung und der Forschung und Bildung in Bezug auf die Veränderung der internationalen Lage (Konflikt zwischen Russland und der Ukraine, Covid-19 und Entwicklung der Fernarbeit, Einsatz des Blockchains zur Verschlüsselung von Transaktionen und Kommunikationen, Durchbruch der künstlichen Intelligenz).

Wenn wir zurück auf den Themenkomplex Energie, Wirtschaft, Optimierung, Nachhaltigkeit in den Jahren 1995-2000 schauen, dann sehen wir nur eine Erwähnung der Energie im Rahmen von Rechenzentrum in Bezug auf den FCKW-Halon-Verbot, die von Frau Ministerpräsidentin Monika Ganseforth (SPD) am 16.03.1995 aufgegriffen wird. Frau Ganseforth bedauert, dass dieser Verbot u.a. für Rechenzentren und EDV-Anlagen noch nicht gelte. Aebischer hat dann Recht, wenn er sagt, dass die Strom- und im Allgemeinen die Energiefrage bei Rechenzentren von der deutschen Politik kaum berücksichtigt wurde. In den Debatten des Bundestags bleibt es so fast bis heute, wie unsere Abbildung nahelegt, die jedoch eine leichte Wiederbelebung vom Themenkomplex Energie, Wirtschaft, Optimierung, Nachhaltigkeit ab 2022-2023 zeigt. Wenn wir diese letzte Zeit fokussieren, merken wir, dass Rechenzentren als Hebel einer grünen Ökonomie, die von wissenschaftlichen Innovationen unterstützt wäre, die deutsche Politik uneins lässt. Dass Rechenzentren eine immer wichtigere Rolle in diesem Zusammenhang spielen, ist unumstritten. Was umstritten ist, ist der Preis, den die Gesellschaft dafür zahlen sollte (vgl. dazu die kontroversen Debatten um Digitalisierung anhand von erneuerbaren Energiequellen im Protokoll des Bundestages vom 17.05.2023; vgl. auch dazu die Wortmeldung vom FDP Mitglied Stephan Seiter zur möglichen Versorgung von deutschen Rechenzentren mit Atomkraftwerken im Protokoll des Bundestages vom 23.02.2024). In den Debatten im Bundestag kommt deutlich zum Vorschein, dass es daran gezweifelt wird, wie Energieeffizienz gelingen kann, ohne dass eine solche Energieeffizienz zu weniger Energieleistung führen würde, was sich Deutschland nicht erlauben kann. Wie gewährleistet man die Wettbewerbsfähigkeit Deutschlands mit Rechenzentren, die einerseits in allen Bereichen der Gesellschaft immer wichtiger werden, andererseits aber immer mehr Strom verbrauchen und Co2 Emissionen produzieren würden? Kann man eine solches Problem überhaupt lösen? Genau an dieser Frage bestellen Instanzen der deutschen Politik wie  in der Expertenliteratur zu Rechenzentren einen Ansatz formuliert, damit es versucht wird, die Öffentlichkeit davon zu überzeugen, dass ein solches Problem gelöst werden kann.

* Energieeffiziente Rechenzentren



Dies ist ein gutes Beispiel dessen, was Sackmann mit seinem figurationssoziologischen Ansatz als Machtbalance versteht



** Erster Schritt: Definieren

Verortungen kann man ab der Arbeit am Selbstverständnis


Die Rechenzentren haben nach wie vor folgende Probleme:

*** Ausdruck der Materialität:

Bau und Gebäude sind sehr wichtig, deshalb die Räumlichkeit in diesem Zusammenhang eine große Rolle spielt, die mit den ersten Studien zu Rechenzentren als erstes Kriterium für die Definition der Rechenzentren verwendet wird.

Am Anfang in der Entwicklung von Rechenzentren sieht man sie außerhalb von Großstädten angesiedelt, weil die Preise für Errichtung von Gebäuden weniger hoch sind. Das ist die Zeit der Entwicklung von kleinen Rechenzentren für die spezifischen Bedürfnissen von Firmen. Diese Rechenzentren kommunizieren nicht miteinander, sondern sie stehen nebeneinander im Raum.

Mit der Entwicklung von Internet in den 1990er Jahre und die Entstehung von Machtakteure der Medienbranche in den Städten geht ein dreifaches Trend a) der Verbindung zwischen den besonderen Rechenzentren über das Internet, b) der Teilung von Räumlichkeiten innerhalb von Rechenzentren und b) der Errichtung von Rechenzentren in Großstädten, in denen die Machtakteure der Medienbranche angesiedelt sind.

Mit der weiteren Entwicklung von Internet und digitalen Kommunikationen in der Form von sozialen Netzwerken und vom cloud computing ab der Jahre 2000 geht ein weiteres dreifaches Trend a) der Vergrößerung der Räumlichkeiten von Rechenzentren, die deshalb in industriellen Vierteln von Großstädten aufgebaut werden, wo größere Flächen verfügbar sind b) des Mehrbedarfs an Strom, um die Rechenzentren zu versorgen, der von der c) technologischen Entwicklung der rechnerischen Kapazitäten von Servern verursacht wird, die u.a. durch die Verschiebung der Rechenkapazität von CPU auf GPU deutlich beschleunigt wird (mehr Berechnungen per Sekunde), was mehr Strom verlangt.

*** Ausdruck der Schnittstelle mit Wissen:

An diesem Punkt erreicht man die Schnittstelle zwischen dem materiellen Bedarf von Rechenzentren und die Mehrinvestition in die Technik selbst. Hier auch ist diese Mehrinvestition immer im Hintergrund der Errichtung von Gebäuden für Rechenzentren anwesend, weil Rechenzentren spezielle Gebäudetechniken verlangen, um Pannen zu vermeiden (Abkühlung von Räumlichkeiten, Isolierung gegen Feuchtigkeit, Bodentechnik um Bodenstürtze zu vermeiden). Dieser Punkt gewinnt an Bedeutung mit der technischen Entwicklung von Rechenzentren, die ein qualifiziertes Personal verlangen, das im Fall von Pannen intervenieren kann. Wenn am Anfang der Entwicklung von Rechenzentren insbesondere Personal aus dem Bausektor als wichtig für die Gebäudetechnik erscheinen, werden mit der Entwicklung der Rechentechnik Techniker und Ingenieure wichtig.

Das über wirtschaftliche Sektoren ebenfalls wissenschaftliche Einrichtungen für die Errichtung und das Funktionieren von Rechenzentren mit einbezogen werden müssen, führt zur Vorstellung, dass Rechenzentren neue wirtschaftliche Märkte eröffnen und einen konkreten Schritt ein eine reale wissensbasierte Wirtschaft leisten. In diesem Zusammenhang wird insbesondere von der Politik erwartet, dass Rechenzentren Arbeit schaffen werden und somit einen bedeutsamen Beitrag zum wirtschaftlichen Wachstum leisten werden. An der Seite der Politik wird erwartet, dass 1 Job im Rahmen von Rechenzentren bis 7.5 in der lokalen bzw. regionalen Wirtschaft kreiert. Selbst heute spricht Donald Trump von der Beschaffung von 100.000 Arbeitsplätzen durch neue Rechenzentren.

Für die Machtakteure der Medien, die mittelbar und unmittelbar mit dem Aufbau von Rechenzentren beschäftigt sind, muss diese politische Erwartung einbezogen werden, damit sie von der Investition öffentlicher Gelder zur Konsolidierung ihrer Einflussstrategie in der Gesellschaft profitieren können. Aber es ist kompliziert.

*** Ausdruck Machtbalance bzw. Abweichung von der Satellisierung der Wirtschaft, der Wissenschaft und der Politik:

Das erste Problem betrifft den Kernelement vom Selbstverständnis der Machtakteure der Medien, die, wenn sie ihren Einfluss auf die ganze Gesellschaft ausüben wollen, ihre Einflussstrategie unaufhörlich entwickeln müssen. Auf der Ebene von Rechenzentren bedeutet dies, dass solche Rechenzentren ständig funktionieren müssen, auch wenn sie immer größer und in ihrer Verwaltung und Wartung komplizierter werden. Da Rechenzentren Pannen erleben, muss nicht nur die Technik häufig verdoppelt werden, sondern auch die Techniker müssen gefunden werden, die Pannen reparieren können. Mit der raschen technologischen Entwicklung von Serverelementen wie GPU-Chips sind Techniker, die mit diesen neuen Technologien umgehen können, weniger geworden, weil Ausbildungen in diesem Bereich noch nicht existieren bzw. von Hochschulen angeboten werden. Deshalb müssen Machtakteure der Medien nicht nur dafür sorgen, dass die letzte Technologie in ihre Rechenzentren gehen, sondern sie müssen auch dafür sorgen, dass ein kompetentes Personal gefunden wird, das diese Zentren verwalten und warten können.

In diesem Zusammenhang hat man eine Balance der Macht von Machtakteuren der Medien, die daher kommt, dass die Entwicklung von ihrem Einflussstrategie auf die Gesellschaft nicht gestaltet werden kann, wie sie es sich wünschen, was dann komplizierter macht, die Politik davon zu überzeugen, dass es mit öffentlichen Geldern in ihren Rechenzentren investiert werden sollte. Manche von diesen Akteuren wie etwa Mark Zuckerberg von Meta greifen dann in die eigene Gelder, um eigene Rechenzentren zu errichten, die dann mit der eigenen Infrastrukturen an Personal und Energieversorgung funktionieren sollten. Hier sieht man ein Beispiel, wie ein Akteur in einer Figuration versucht, die Machtbalance zwischen den Akteuren zu beeinflussen, um mehr macht beim Einfluss der anderen Akteuren in dieser Figuration sowie mittelbar auch in den anderen Figuration zu beeinflussen.

*** Zurück zur Machtbalance:

Wie sie von Elias konzipiert wird (Beispiel Fussball), ist die Machtbalance dadurch verursacht, dass Gegenakteure die Handlung von Akteuren ausbremsen bzw. einschränken, die sich in der gleichen Figuration mit den Akteuren befinden, dagegen sie kämpfen. In der Theorie der Relation entspricht diese Auffassung von Machtbalance eine Blockadestrategie im Sinne einer klaren Verteidigung von der eigenen Ordnung von Verhältnissen auf der Grundlage der Aufbewahrung der eigenen Legitimität bzw. des eigenen Selbstverständnis. Mit diesem Beispiel der Rechenzentren sieht man, dass Elias' Auffassung von Machtbalance eine grundsätzlichere Vorstellung von Macht voraussetzt, die im Rahmen des Figurationsansatzes von Elias nicht in ihren Folgen thematisiert wird: die Macht durch Allianzen. Um das Beispiel des Fussballs wieder zu erwähnen, kann man sagen, dass Fussballmanschaften andere Fussballmanschaften brauchen, um ihre sportliche Leistungen bzw. ihre Techniken, Taktiken und Strategien zu verbessern, die weniger als "Gegener" wahrgenommen werden, sondern mehr als "Partner" im Rahmen von einem strukturierten Wettbewerb gelten, die erlauben, an der Optimierung der eignen Organisation des Spieles zu arbeiten, um sie möglicherweise langfristig zu steigern. Dass am Ende eine Mannschaft das Pokal gewinnt, ist für die Attraktivität dieser Mannschaft gut, aber es ist insgesamt weniger als die langfristige Steigerung der eigenen Optimierung wichtig. Oder anders gesagt: Einmal zu gewinnen ist gut, regelmäßig zu gewinnen ist besser. Damit gewinnt man an Einfluss auf die anderen Mannschaften im Sinne der Spielorganisation und der Spieler in dieser Organisation, wie man insgesamt an Attraktivität für weitere Akteure innerhalb und außerhalb der Fußballbranche gewinnt.

Relationsstrukturen versuchen, sich langfristig auf weitere Relationsstrukturen zu verbreiten, weshalb sie unaufhörlich an Allianzen als privilegierte Strategie der eigenen Verbreitung und der Steigerung der eigenen Legitimität und damit der eigenen Macht arbeiten.

*** Energieeinsparung als Rhetorik zur Optimierung des Selbstverständnisses von Machtakteuren der Medien:

Natur als Problem der Umverteilung von Ressourcen.



Lebensläufe werden entsprechend als relationale Komplexe konzeptualisiert, die Symbolen und formale Prozessen von gesellschaftlichen Instanz einbeziehen, davon strukturiert werden und sie ebenfalls strukturieren.

* Einleitung. Was passiert um die KI

Die Idee von dieser Arbeit ist aus den verschiedenen Gesprächen entstanden, die ich mit Kollegen zur Entwicklung der künstlichen Intelligenz (KI) durchgeführt habe, und die nach der Veröffentlichung vom Prognose "AI-2027" der Autoren Daniel Kokotajlo, Scott Alexander, Thomas Larsen, Eli Lifland und Romeo Dean an Brisanz gewonnen haben [cite:@ai-2027].
