#+Bibliography: /home/cpsoz/Github/rom/CP-ROM.bib

Im Oeuvre Reinhold Sackmanns hat uns einen Ansatz besonders interessiert, den er im Rahmen seiner unterschiedlichen Arbeiten zur Demographie, zur Lebenslaufsoziologie und zu gesellschaftlichen Instanzen der Sozialisation wie den (Hoch)Schulen, dem Arbeitsmarkt oder dem Rentensystem entwickelt hat. Dieser Ansatz finden wir in seinen Arbeiten unterschiedlich ausgedruckt. Nehmen wir etwa die Schlussfolgerungen seiner Habilitationsschrift, wenn er eine Bilanz zur Lebenslaufsoziologie wie folgt zieht: "An den Anfängen dieser Disziplin (...) stand die Vorstellung, daß Alter neben seiner biologischen Komponente auch gesellschaftlich kulturelle Elemente enthält. Gesellschaft war ein Nebenfaktor, der wahrgenommen werden sollte. In der Theorie des institutionalisierten Lebenslaufs gewann die Vorstellung Kontur, daß die modernen gesellschaftlichen Institutionen (...) spezifische Lebensläufe kontitutieren" [cite:@sackmann98:_konkur_gener_arbeit, 228-229]. Dabei legt Sackmann nah, dass sich die künftige Forschung in der Lebenslaufsoziologie mit der Art und Weise auseinandersetzen sollte, wie Lebensläufe als eingebettete Prozesse an der Schnittstelle der Biographien von Akteuren und der formalen Operationen von gesellschaftlichen Instanzen entstehen und von einer solchen Einbettung strukturiert werden. "Lebensläufe", wie er in einem späteren Beitrag sagt, "vollziehen sich eingebettet, in Gruppen, in Gemeinschaften, Gesellschaften und v.a. Organisationen" [cite:@sackmann07:_leben_biogr, 206]. Dieser Ansatz ist aus den folgenden Gründen interessant.

Sackmann versteht Lebensläufe nicht mehr im geläufigen soziologischen Sinn von "trajectoires", die den Fokus auf den Weg der Akteure von gesellschaftlichen Instanzen der Sozialisation zu weiteren gesellschaftlichen Instanzen der Sozialisation setzen. Damit wird gesagt, das gesellschaftliche Sozialisationsinstanzen wie etwa (Hoch)Schulen oder Arbeitsmarkt mehr als nur "verpflichtende Anlaufstationen" von Akteuren sind [cite:@latour05:_reass_social], die Akteure registrieren würden und je nach Sozialisationserfolg unterschiedlich auf weitere gesellschaftliche Bahnen umverteilen würden. Gesellschaftliche Instanzen sind keine irreflexive Orte der Vergebung von Titeln und Rechten, sondern sie geben den Akteuren Einschreibungsmöglichkeiten in der Gesellschaft und reflektieren entsprechend über ihre Rolle in diesem Zusammenhang. Auch zu diesem Zweck entwickeln gesellschaftliche Instanzen dauernd formale Verfahren, die Orientierungsmuster bzw. "Leitbilder" für die Akteure schaffen und deshalb auf ihre Laufbahnen wirken [cite:@sackmann07:_leben_biogr, 206]. Dass eine solche Wirkung auch unintendierte Folgen hat und Ungleichheiten zwischen Akteuren bzw. Akteurgenerationen generiert, hat Sackmann mehrmals im Sinne einer kritischen soziologischen Betrachtung von gesellschaftlichen Instanzen unterstrichen [cite: vgl. etwa @sackmann15:_bedeut_auswah_erzeug_bildun; vgl. auch @sackmann19:_mechan_eliteb]. Aber eine kritische Betrachtung von gesellschaftlichen Instanzen reicht allein nicht aus. Nach Sackmann müssen ebenfalls Korrekturmaßnahmen von gesellschaftlichen Instanzen abgebildet werden, die darauf abzielen, Maßnahmen und entsprechende formale Verfahren zur Einschränkungen bzw. Schrumpfung der Ungleichheitsproduktion zu definieren.

Mit diesem konstruktiven Korrelat zur kritischen Betrachtung von gesellschaftlichen Instanzen bringt Sackmann seinen Ansatz zur Vollendung: Weil Kollektivakteure als Teil des Einschreibungskontextes fungieren, den sie mit den Akteuren aufbauen und innerhalb dessen die Laufbahn von solchen Akteuren strukturiert wird, ist es aus Sicht einer soziologischen Makroperspektive nicht ausreichend, nur die Defizite von Kollektivakteuren in ihren Wechselwirkungen mit Einzelakteuren hervorzuheben. Es muss ebenfalls verstanden werden, wie gesellschaftliche Instanzen an ihren formalen Operationen Arbeiten, um sie nicht nur im Sinne der Stärkung der eigenen Position in der Gesellschaft zu verbessern, sondern auch im Sinne der Förderung des Lebenslaufs ihrer Adressaten bzw. der Zuverlässigkeit von (positiven wie negativen) Sanktionsoperationen an der Wurzel der (Um)Verteilung von Akteuren auf gesellschaftliche Tätigkeiten, entsprechende Bereiche und dort aktive Instanzen. Aus einem solchen Ansatz ziehen wir zwei wichtigen Botschaften.

Die erste Botschaft betrifft den gesellschaftlichen Zusammenhalt. Der gesellschaftliche Zusammenhalt ist kein Zustand, sondern eine Dynamik [cite:@sackmann98:_konkur_gener_arbeit, 82], die eine eigene Elastizität je nachdem hat, wie gut oder weniger gut die Lebensläufe durch die Einbettung von Akteuren und gesellschaftlichen Instanzen strukturiert werden. In seinem Ansatz denkt Sackmann eine solche Dynamik mit dem Begriff der Figuration von Norbert Elias, vom dem er insbesondere die Interdependenz der protagonistischen und antagonistischen Akteuren in Figurationen sowie die Machtbalancen hervorhebt (ebd., bes. 73ff.). Figurationen sind keine Zustände, sondern Zusammenstellungen von Einzel- wie Kollektiveakteuren und Nicht-Akteuren, die sich in Zeit und Raum mehr oder weniger verbreiten oder schrumpfen. Die zweite Botschaft betrifft diese Verbreitung bzw. Schrumpfung. Im Rahmen von Figuration denkt sie Elias als von Machtbalancen innerhalb von Figuration sowie von den Machtbalancen zwischen Figurationen abhängig, was bedeutet, dass (Kollektiv)Akteure in Figuration "nicht gleich stark" sind (ebd. 75), weshalb auch Asymmetrien entstehen, die jedoch keine radikalen Asymmetrien im Sinne der Monopolisierung von Macht bilden: "selten gelingt es einer Konfliktpartei, die andere vollkommen zu entmachten" (ebd.). Die Macht wird in Figurationen eng mit der Interdependenz von den unterschiedlichen (Kollektiv)Akteuren verbunden und somit dynamisiert, was im Begriff "Balance" wiedergegeben wird -- die Macht ist im Wechselspiel der (Kollektiv)Akteuren eingebettet und wird im Laufe der Strukturierung der Lebensläufe von Einzelakteuren und der Position von gesellschaftlichen Instanzen mitstrukturiert. Einmal figurationssoziologisch aufgefasst, erscheinen Lebensläufe von Einzelakteuren und Generationen von Akteuren nicht mehr als individuelle Mikrophänomene "neben" der Gesellschaft als Makrophänomen, sondern eine solche Unterscheidung ist überflüssig, weil sie durch ein prozedurales Verständnis von Figurationen als Einbettungs- bzw. Einschreibungskontexte von unterschiedlichen gesellschaftlichen Dimensionen ersetzt wird. Ein solcher Ansatz führt dann zur analytischen folgenden Frage: Was haben wir für Figurationen in unseren Gesellschaft mit welchen Folgen für die Handlung in dieser Gesellschaft und schließlich für diese Gesellschaft selbst?

Eine solche Frage teilen wir in einem etwas anderen theoretischen Rahmen, den wir mit dem Versuch skizziert haben, eine Theorie der Relation anzubieten, die Relation nach einem Makroansatz definiert und entwickelt [cite:@papilloud22:_skizz_theor_relat]. Verglichen mit dem figurationssoziologischen Ansatz Sackmanns geht es in diesem Theorierahmen darum, die Einbettungszusammenhänge radikaler als Relationsstrukturen zu konzipieren, die Ordnungen von Verhältnissen mit (Kollektiv)Akteuren, Nicht-Akteuren und Medien darstellen, die sich nach einer spezifischen Dynamik entwickeln bzw. die verbreitet oder geschrumpft werden. Wichtig dabei bleibt der Ansatz, den wir im Rahmen Sackmanns Deutung der Figuration Elias' zusammengefasst haben: Relationsstrukturen stellen stratifizierte Einbettungs- bzw. Einschreibungskontexte von gesellschaftlichen Phänomenen, Akteuren und Kollektiven in der Form von Verhältnissen dar, die nach einer spezifischen Dynamik der Balance von all möglichen Verhältnissen strukturiert werden, was wiederum eine solche Dynamik strukturiert bzw. verbreitet, be- oder entschleunigt, schrumpfen lässt oder korrigiert. Im Rahmen eines solchen Rahmens bewegt sich die nachfolgende einführende Untersuchung vom Kollektivakteur Rechenzentren in Deutschland, mit der wir einen Beitrag zur Frage leisten wollen, welche Verhältnisse Rechenzentren in unserer Gesellschaft in den Vordergrund bringen und welche Folgen entstehen daraus für weitere Ordnungen von Verhältnissen. Als erster Schritt in dieser Untersuchung wollen wir verstehen, was Rechenzentren für eine Art von gesellschaftlicher Instanz sind.

* Rechenzentren in Deutschland. Eine Verortung

Ein erstes Problem, das den Rahmen der Theorie der Relation lösen will, betrifft die Diskrepanz zwischen dem Realen und dem Formalen bei der Verortung von Instanzen der Gesellschaft bzw. bei der Beschreibung der Position von gesellschaftlichen Instanzen in Ordnungen von Verhältnissen. Real können wir Instanzen und Instanzfraktionen möglicherweise in unterschiedlichen Orten der Gesellschaft finden. Nehmen wir das Beispiel der Forschung: Sie kann als akademische Forschung im Rahmen von Hochschulen oder von Forschungszentren stattfinden, aber sie kann auch in Abteilungen von Industrien oder Firmen sowie auch im Rahmen der Politikberatung oder des Journalismus praktisiert werden. Strukturell setzt sie gleiche Rahmenbedingungen überall in Bezug auf die Mittel sowie auf die Zwecken voraus: einen Zugang zu einer zuverlässigen Information, die bei Bedarf durch Einbezug von weiteren Akteuren, Kollektiven, Nicht-Akteuren und Medien kontrolliert und vertieft wird, die verarbeitet eine breite oder weniger breit Öffentlichkeit erreicht. Forschung kann folglich überall in der Gesellschaft auftauchen. Aber nicht überall in dieser Gesellschaft ist Forschung gleich Forschung, sondern es hängt davon ab, sagen wir im Rahmen der Theorie der Relation, welche Ordnung von Verhältnisse Forschung einerseits strukturiert und Forschung andererseits unterstützt. Damit wird verstanden, dass die Forschung an Universitäten im Vergleich etwa zur Forschung in Firmen nicht besser/schlechter, wichtiger/weniger wichtig, schneller/langsamer, stärker/schwächer wäre, sondern Verhältnisse zwischen Akteuren, Instanzen, Nicht-Akteuren und Medien in der Forschung anders gestaltet bzw. eine andere Relationalität oder relationale Dynamik zwischen ihnen entwickelt.

Im Rahmen der Theorie der Relation haben wir versucht, diesen Ansatz in seinen letzten Folgen zu denken. Daraus ergibt sich, dass die relationale Dynamik einer Ordnung von Verhältnissen als Leitbild für die Entwicklung der gesellschaftlichen Zirkulation von Akteuren und die Positionierung bzw. Verortung von gesellschaftlichen Instanzen funktioniert, die sie beeinflussen. Weiter haben wir nahegelegt, dass eine Ordnung von Verhältnissen die anderen Ordnungen von Verhältnissen über ihre eigenen Instanzen nach ihrer eigenen Dynamik zu beeinflussen versucht, um sich auf die anderen Ordnungen von Verhältnissen so zu verbreiten, als ob diese anderen Ordnungen von Verhältnissen Merkmale ihrer Dynamik wären. Im Zusammenhang dieses Beitrages wollen wir die zwei Anhaltspunkte dieser Überlegung miteinander enger verbinden, indem wir ausgehend von der Verortung der Rechenzentren in Ordnungen von Verhältnissen zeigen, wie sie innerhalb von ihrer Ordnung von Verhältnissen andere Ordnungen von Verhältnissen zu beeinflussen beabsichtigen.

** Erster Schritt: Definieren

Verortungen kann man ab der Arbeit am Selbstverständnis


würden wir uns jedoch auf zwei Punkten , sondern wir möchten zeigen, wie durch die Beobachtung der Priorisierung von Verhältnissen Rechenzentren in Ordnungen von Verhältnissen verortet werden können, und wie sie ab dieser Position

Deshalb auch die entsprechende unterschiedliche Verortung von Forschung

Dies verhält sich am Beispiel der Rechenzentren nicht anders.





Lebensläufe werden entsprechend als relationale Komplexe konzeptualisiert, die Symbolen und formale Prozessen von gesellschaftlichen Instanz einbeziehen, davon strukturiert werden und sie ebenfalls strukturieren.

* Einleitung. Was passiert um die KI

Die Idee von dieser Arbeit ist aus den verschiedenen Gesprächen entstanden, die ich mit Kollegen zur Entwicklung der künstlichen Intelligenz (KI) durchgeführt habe, und die nach der Veröffentlichung vom Prognose "AI-2027" der Autoren Daniel Kokotajlo, Scott Alexander, Thomas Larsen, Eli Lifland und Romeo Dean an Brisanz gewonnen haben [cite:@ai-2027].
