#+Bibliography: /home/cpsoz/Github/rom/CP-ROM.bib

Im Oeuvre Reinhold Sackmanns hat uns einen Ansatz besonders interessiert, den er im Rahmen seiner unterschiedlichen Arbeiten zur Demographie, zur Lebenslaufsoziologie und zu gesellschaftlichen Instanzen der Sozialisation wie den (Hoch)Schulen oder dem Arbeitsmarkt entwickelt hat. Dieser Ansatz finden wir in seinen Arbeiten unterschiedlich ausgedruckt. Nehmen wir etwa die Schlussfolgerungen seiner Habilitationsschrift, wenn er eine Bilanz zur Lebenslaufsoziologie wie folgt zieht: "An den Anfängen dieser Disziplin (...) stand die Vorstellung, daß Alter neben seiner biologischen Komponente auch gesellschaftlich kulturelle Elemente enthält. Gesellschaft war ein Nebenfaktor, der wahrgenommen werden sollte. In der Theorie des institutionalisierten Lebenslaufs gewann die Vorstellung Kontur, daß die modernen gesellschaftlichen Institutionen (...) spezifische Lebensläufe kontitutieren" [cite:@sackmann98:_konkur_gener_arbeit, 228-229]. Dabei legt Sackmann nah, dass sich die künftige Forschung in der Lebenslaufsoziologie mit der Art und Weise auseinandersetzen sollte, wie Lebensläufe als eingebettete Prozesse an der Schnittstelle der Biographien von Akteuren und der formalen Operationen von gesellschaftlichen Instanzen entstehen und von einer solchen Einbettung strukturiert werden. "Lebensläufe", wie er in einem späteren Beitrag sagt, "vollziehen sich eingebettet, in Gruppen, in Gemeinschaften, Gesellschaften und v.a. Organisationen" [cite:@sackmann07:_leben_biogr, 206]. Dieser Ansatz ist aus den folgenden Gründen interessant.

Sackmann versteht Lebensläufe nicht mehr im geläufigen soziologischen Sinn von "trajectoires", die den Fokus auf den Weg der Akteure von gesellschaftlichen Instanzen der Sozialisation zu weiteren gesellschaftlichen Instanzen der Sozialisation setzen. Damit wird gesagt, das gesellschaftliche Sozialisationsinstanzen wie etwa (Hoch)Schulen oder Arbeitsmarkt mehr als nur "verpflichtende Anlaufstationen" von Akteuren sind [cite:@latour05:_reass_social], die Akteure registrieren würden und je nach Sozialisationserfolg unterschiedlich auf weitere gesellschaftliche Bahnen umverteilen würden. Gesellschaftliche Instanzen sind keine irreflexive Orte der Vergebung von Titeln und Rechten, sondern sie geben den Akteuren Einschreibungsmöglichkeiten in der Gesellschaft und reflektieren entsprechend über ihre Rolle in diesem Zusammenhang. Zu diesem Zweck entwickeln gesellschaftliche Instanzen formale Verfahren, die Orientierungsmuster bzw. "Leitbilder" für die Akteure schaffen und deshalb auf ihre Laufbahnen wirken [cite:@sackmann07:_leben_biogr, 206]. Dass eine solche Wirkung auch unintendierte Folgen hat und Ungleichheiten zwischen Akteuren bzw. Akteurgenerationen generiert, hat Sackmann mehrmals im Sinne einer kritischen soziologischen Betrachtung von gesellschaftlichen Instanzen unterstrichen [cite: vgl. etwa @sackmann15:_bedeut_auswah_erzeug_bildun; vgl. auch @sackmann19:_mechan_eliteb]. Aber eine kritische Betrachtung von gesellschaftlichen Instanzen reicht alleine nicht aus. Nach Sackmann müssen ebenfalls Korrekturmaßnahmen von gesellschaftlichen Instanzen abgebildet werden, die darauf abzielen, Maßnahmen und entsprechende formale Verfahren zur Einschränkungen bzw. Schrumpfung der Ungleichheitsproduktion zu definieren. Mit diesem konstruktiven Korrelat zur kritischen Betrachtung von gesellschaftlichen Instanzen bringt Sackmann seinen Ansatz zur Vollendung: Weil Kollektivakteure als Teil des Einschreibungskontextes fungieren, den sie mit den Akteuren aufbauen und innerhalb dessen die Laufbahn von solchen Akteuren strukturiert wird, ist es aus Sicht einer soziologischen Makroperspektive nicht ausreichend, solche Kollektivakteure nur als defizitäre Akteure in ihren Wechselwirkungen mit Einzelakteuren zu beschreiben, die zu ihnen kommen.

Oder anders gesagt: Lebensläufe von Akteuren entwickeln sich in der Wechselwirkung von Akteuren und Instanzen und diese Wechselwirkung zeigt auf der Ebene der Normen und Werte von einer Gesellschaft, dass Instanzen

die solche Instanzen zur . Deshalb wirken sie auf die Lebensläufe von Akteuren


Konsequenzen für die Strukturierung der Lebensläufe von Akteuren selbst. Durch

Lebensläufe werden entsprechend als relationale Komplexe konzeptualisiert, die Symbolen und formale Prozessen von gesellschaftlichen Instanz einbeziehen, davon strukturiert werden und sie ebenfalls strukturieren.

* Einleitung. Was passiert um die KI

Die Idee von dieser Arbeit ist aus den verschiedenen Gesprächen entstanden, die ich mit Kollegen zur Entwicklung der künstlichen Intelligenz (KI) durchgeführt habe, und die nach der Veröffentlichung vom Prognose "AI-2027" der Autoren Daniel Kokotajlo, Scott Alexander, Thomas Larsen, Eli Lifland und Romeo Dean an Brisanz gewonnen haben [cite:@ai-2027].
