#+Bibliography: /home/cpsoz/Github/rom/CP-ROM.bib

* Notizen zum ROM

** Aus Fichter 2007

*** Ausgangslage IKT und RZ im Bezug auf Energie

- Bezug auf die Wirtschaft ist unmittelbar im Vordergrund: "moderne Umweltpolitik muss auch Innovationspolitik sein. Um Wachstums- und Beschäftigungspotenziale zu mobilisieren ist es wichtig, Syner-
gieeffekte zwischen der Verbesserung der Umweltsituation, der Schaffung zukunftsfähiger Arbeitsplätze und der Erhöhung der Wettbewerbsfähigkeit zu identifizieren und zu nutzen." [cite:@fichter07:_zukun_energ_rechen, I]
- Auf der gleichen Seite erfährt man, dass diese Studie im Rahmen von Fallstudien zu 11 strategischen Produktgruppen entstanden ist, die von besonderer Relevanz für die Wettbewerbsfähigkeit Deutschlands und Europas sind: "Besonderes im Blickpunkt stehen dabei die Entwicklung der Wettbewerbsfähigkeit deutscher und europäischer Unternehmen im internationalen Vergleich, ihr Umfeld sowie Ansatzpunkte für eine Stärkung des deutschen und europäischen Innovationssystems." (ebd.)
- Dabei ist die Studien aus einem "Fachdialog des Bundesumweltministeriums zum Thema „Zukunftsmarkt ‚grüne’ Rechenzentren“" mit Partnern aus der Wissenschaft entstanden: Oldenburg Center for Sustainability Economics
and Management (CENTOS) der Universität Oldenburg, dem Fraunhofer Institut für System- und Innovationsforschung (ISI), Karlsruhe sowie dem Institut für Zukunftsstudien und Technologiebewertung (IZT). Diese Gespräche haben am 3.7.2007 stattgefunden. (ebd.)
- Es braucht dringend "innovativen Energieversorgungs-, Kühlungs- und Abwärmenutzungskonzepten" sowie Konzepte für Auditsmaßnahmen, damit das Potential von einem solchen Markt besser benutzt wird [cite:@fichter07:_zukun_energ_rechen, 1]
- Verbindung mit Wissenschaft und Informationsgesellschaft: "Außerdem zählen die Herstellung und Wartung von IKT sowie Software-Häuser und EDV- und datenbankbezogenen Dienstleistungen zu den sogenannten „wissensintensiven Industrien und Dienstleistungen“, die mit Blick auf den Wandel von der Industrie- zur Informationsgesellschaft eine Schlüsselposition einnehmen." (ebd. 3)


| Jahr | Technologie                                   | Strom  | Vergl. Strom.    | Mio. Tonnen Co2 Äquivalent | Prognose Jahr | Prognose Zahl | % vom BIP | Quelle                                   |
|------+-----------------------------------------------+--------+------------------+----------------------------+---------------+---------------+-----------+------------------------------------------|
| 1994 | Informations- und Kommunikationstechnik (IKT) |        |                  |                            |               |               | 4,7       | [cite:@fichter07:_zukun_energ_rechen, 3] |
| 2001 | IKT                                           | 38 TWh | 7,1% Gesamtverbr |                            |          2010 | 55 TWh        |           | [cite:@fichter07:_zukun_energ_rechen, 3] |
| 2005 |                                               |        |                  |                            |               |               | 6,8       | [cite:@fichter07:_zukun_energ_rechen, 3] |
| 2004 | Informations- und Kommunikationstechnik (IKT) |        |                  |                         28 |               |               |           | [cite:@fichter07:_zukun_energ_rechen, 1] |

- Warum der Fokus auf Datacenter: "Innerhalb der IKT-Infrastruktur sind Server und Rechenzentren für den größten Teil des Stromverbrauchs verantwortlich. Außerdem wächst dieser Bereich überdurchschnittlich stark. Daher soll im Folgenden auf den Energieverbrauch und die Energieeffizienzpotenziale von Rechenzentren fokussiert werden." [cite:@fichter07:_zukun_energ_rechen, 4]


| Jahr | Anzahl RZ | Stromverbrauch      | Vergleich Stromverb                                              | Mio. Tonnen Co2 Äquivalent | Prognose Jahr | Prognose Zahl    | % vom BIP | Quelle                                   |
|------+-----------+---------------------+------------------------------------------------------------------+----------------------------+---------------+------------------+-----------+------------------------------------------|
| 2006 |    50.000 | 8.67 TWh            | 1,5fach der Jahresstromerzeugung des Atomkraftwerkes Brunsbüttel | 5,6                        |          2010 | 50% Co2 Äq. mehr |           | [cite:@fichter07:_zukun_energ_rechen, 1] |
|      |           | 21 TWh eingesparrt  | Mit energieeffizienten Technologien auf breiter Front            | 13,6 eingesparrt           |     2007-2010 |                  |           | [cite:@fichter07:_zukun_energ_rechen, 1] |
|      |           | 2,5 Mrd. € Einspar. |                                                                  |                            |               |                  |           |                                          |

*** Das Problem der Definition

- "Bislang gibt es keine allgemein gültige Definition des Begriffs „Rechenzentrum“ bzw. „data centre“" [cite:@fichter07:_zukun_energ_rechen, 5]
- Raumorientierte Definition von Datacenter (ebd., 5-6):

  | Name RZ                        | Räumlichkeit                                           |
  |--------------------------------+--------------------------------------------------------|
  | „server closet“                | (weniger als 20 qm 4 , 1 – 2 Server)                   |
  | „server room“                  | (weniger als 50 qm, einige Duzend Server)              |
  | „localized data center         | (weniger als 100 qm, Duzend bis Hunderte von Servern)  |
  | „Mid-tier data center“         | (bis 500 qm, Hunderte von Servern)                     |
  | „Enterprise class data center“ | (größer als 500 qm, Hunderte bis Tausende von Servern) |

- Aus dieser Typologie wird die folgende Definition von RZ vorgeschlagen: "Mit „Rechenzentrum“ soll hier ein Gebäude bzw. sollen hier Räumlichkeiten bezeichnet werden, in denen die zentrale Rechentechnik (Server, aber auch die
zum Betrieb notwendige Infrastruktur) einer oder mehrerer Firmen oder Organisationen untergebracht sind. Dabei muss es sich zumindest um einen eigenständigen Raum mit sicherer Stromversorgung und Klimatisierung handeln." (ebd. 6); nach dieser Definition werden RZ von einfachen Serverschränken unterschieden, weil Letztere nicht "zwangsläufig in einem eigenständigen Raum untergebracht sein müssen" (ebd.). D.h. in der Tabelle davor werden nur die drei letzten Zeilen als RZ anerkannt werden;
- Eine zusätzliche technikorientierte Definition wird vorgeschlagen, um den Kern von RZ zu definieren (ebd., 7): im Kern beziehen RZ die drei folgenden IT-Komponenten Server, Speicher, Netzwerkausrüstung (ebd., 7);
- Zu dieser technikorientierte Definition vom Kern der RZ kommen periphäre Elemente, die auch eine wichtige Rolle spielen: "Für deren sicheren und verlässlichen Betrieb sind aber darüber hinaus noch andere Energie verbrauchende Komponenten wie die unterbrechungsfreie Stromversorgung, die Stromverteilung sowie die Klimatisierung und Kühlung von Nöten." (ebd., 8)

*** Das Problem der Anzahl an RZ

- niemand weiss genau, wie viele RZ es in DT, in Europa oder weltweit gibt: "Für die Ermittlung und das Monitoring des Energieverbrauchs von Rechenzentren ist die Frage zentral, wie viele Rechenzentren welchen Typs und welcher Größe es gibt. Hierzu existieren bis dato weder in der Wissenschaft noch bei den Branchenverbänden oder den einschlägigen Marktforschungseinrichtungen Statistiken." (ebd., 8)
- deshalb muss es geschätzt werden (Tabelle unten, reproduziert aus ebd. 9):

  | Regionen | Anzahl RZ 2007 | Anzahl Server 2007 | Durchschnitt Server pro RZ | Durschnitt. Raum in qm |
  |----------+----------------+--------------------+----------------------------+------------------------|
  | DT       |         50.000 |          1.592.484 |                         32 |                     90 |
  | EU       |        330.000 |          7.560.072 |                         23 |                     90 |
  | Welt     |      3.000.000 |         32.000.000 |                         11 |                     90 |

- Für die US gibt es erste Statistiken ab 2007 (ebd.); dort sieht man, dass RZ
